---
# Ansible requirements file
# Install with: ansible-galaxy install -r requirements.yml

collections:
  - name: community.general
    version: ">=4.0.0"
  - name: ansible.posix
    version: ">=1.0.0"