---
galaxy_info:
  role_name: shell_config
  author: Developer Automation Package
  description: Configure shell environment (zsh/oh-my-zsh)
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: CentOS
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 35
        - 36

dependencies: []